name: GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate stats images
        uses: jstrieb/github-stats@master
        with:
          username: itsabdul-dev
          exclude_repos:
          exclude_langs:
          github_token: ${{ secrets.GITHUB_TOKEN }}
